name: widgetbook_workspace

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
  uistudy:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  widgetbook_generator: ^3.15.0
